# resources:
# #  - name: connecting_resource_node_test
# #    type: PropertyBag
# #    configuration:
# #      key1: value1
# #      key2: value2
#  - name: resource_pipelines
#    type: GitRepo
#    configuration:
#      gitProvider: github_neha
#      path: neha-mishraa/pipelines
#      files: 
#        include: ^README.md$
#      branches:
#        include: ^{{gitBranch}}$
# #      buildOn:
# #        commit: true

pipelines:
             
  - name: testingVersion123
    steps:
#       # - name: test_step
#       #   type: Bash
# #         configuration:
# #          requiresApproval:
# #            approvers:
# #              - admin
#         #            notifications:
#         #              - integrationName: pipelines_mqtest_slack
#         # execution:
#         #  onExecute:
#         #    - echo "Got the approval"
#       - name: myStep1
#         type: Bash
#         configuration:
# #           nodePool: new-dynamic-nodepool
#           environmentVariables:
#             # readOnly:
#             env1: 
#               description: env var value
#               default: first
#               allowCustom: true
#               values:
#                 - first
#                 - second
#                 - third
#             env2: value2
#           inputResources: 
#             - name: resource_pipelines
#           integrations:
#             - name: github_neha
#  #            - name: slackTest
#  #            - name: smtpNotification
#         execution:
#           onExecute:
# #             - printenv
#             # - pushd $res_resource_pipelines_resourcePath
#             # - ls
#             - echo "hi"
#             - echo "env1 - $env1"
#             - echo "env2 - $env2"
#             # - touch foo.txt
#             # - echo 'This is a test' > foo.txt
#             # - add_run_files foo.txt bar.txt
# #           onSuccess:
# #             - pushd $res_resource_pipelines_resourcePath
# #             - ls
      - name: myStepTestVersion
        type: Bash
#         configuration:
#          inputSteps:
#            - name: myStep1
# #          nodePool: u20dynamic
#          integrations:
#            - name: github_neha
           # - name: genericInt
        execution:
          onExecute:
            - | 
               local rt_version=$(curl -s "https://versions.jfrog.info/latestVersions" | jq -r '.artifactory.official_release'); echo "$rt_version"
#             - restore_run_files bar.txt testResults
#   - name: testing2
#     steps:
#       - name: myStep2
#         type: Bash
#         configuration:
# #          nodePool: u20dynamic
#          integrations:
#            - name: github_neha
#            # - name: genericInt
#         execution:
#           onExecute:
#             - echo "hi"
#             # - echo "${int_genericInt_mykey1}"
#             # - echo "${int_genericInt_mykey2}"
#   - name: testing3
#     steps:
#       - name: myStep3
#         type: Bash
# #         configuration:
# #          nodePool: c7dynamic
#         execution:
#           onExecute:
#             - echo "hi"
         
#   - name: testing4
#     steps:
#       - name: myStep4
#         type: PowerShell
# #         configuration:
# #          nodePool: win_2019
#         execution:
#           onExecute:
#             - echo "hi"
            
            
#   - name: neham
#     steps:
#       - name: myStep5
#         type: PowerShell
#         execution:
#           onExecute:
#             - echo "hi"
            
  


# # resources:
# #   - name: R_CronTrigger_resource
# #     type: CronTrigger
# #     configuration:
# #       interval: "* * * * *"
# #       branches:
# #         include: "^master$"
# #         exclude: "^test$"

# # pipelines:
# #   - name: R_CronTrigger_pipe
# #     steps:
# #       - name: R_CronTrigger_step
# #         type: Bash
# #         configuration:
# #           inputResources:
# #             - name: R_CronTrigger_resource
# #         execution:
# #           onExecute:
# #             - echo hello


# # pipelines:
# #   - name: node_test_
# #     steps:
# #       - name: nodeTestStep
# #         type: Bash
# #         configuration:
# #           nodePool: u18dynamic
# #           outputResources: 
# #             - name: connecting_resource_node_test
# # #               trigger: false
# #           integrations:
# #             - name: github_neha
# #         execution:
# #           onExecute:
# #             - write_output connecting_resource_node_test "test=value"

# #       - name: c7dynamic
# #         type: Bash
# #         configuration:
# #           nodePool: c7dynamic
# #           inputResources:
# #             - name: connecting_resource_node_test
# #         execution:
# #           onExecute:
# #             - printenv
# #             - docker images
            
# #       - name: u20dynamic
# #         type: Bash
# #         configuration:
# #           nodePool: u20dynamic
# #           inputResources:
# #             - name: connecting_resource_node_test
# #         execution:
# #           onExecute:
# #             - printenv
# #             - docker images

# #       - name: win_2019
# #         type: PowerShell
# #         configuration:
# #           nodePool: win_2019
# #           inputResources:
# #             - name: connecting_resource_node_test
# #         execution:
# #           onExecute:
# #             - write-output "Hi"
# #             - docker images
